### ISSUE TITLE
'New decision' email should have link to the decision

### ISSUE THREAD

**Issue by chrismear** [emmapersky/one-click-orgs#108]
Currently has no links.

**Comment by oskarpearson** [comment]
This is the file notify_new_decision.text.erb, as per IRC conversation 20:50 29 April 2010 #onelickorgs on freenode

**Comment by chrismear** [comment]
Add link to decision to 'new decision' email. Closed by 0caaaa3a207dc8e8a1278fe458804883460ce146.
