### ISSUE TITLE
Creating a proposal should cause an automatic 'support' vote

### ISSUE THREAD

**Issue by alexmuller** [emmapersky/one-click-orgs#113]
When creating a new proposal, the user who created it shouldn't have to vote, they should just be placed in support of it… shouldn't they?

**Comment by chrismear** [comment]
Makes sense to me. The only cases I think of where you'd want to make a proposal and then oppose it are severely dysfunctional.

**Comment by chrismear** [comment]
This ticket now at:

https://github.com/oneclickorgs/one-click-orgs/issues/113
