### ISSUE TITLE
Update induction process to use interface closer to core app

### ISSUE THREAD

**Issue by chrismear** [emmapersky/one-click-orgs#118]
An idea from our UX consult session: instead of using the current wizard interface for the induction process, use the app's normal interface to allow the user to set the members, constitutional settings etc. for their proto-organisation, all using the same tools they'll be using after they actually found the organisation. The only difference is that all of the changes will be enacted immediately instead of requiring a vote, and we need to display additional guidance copy relevant to the in-progress state of the organisation.

**Comment by chrismear** [comment]
It occurs to me that this could be a good place to start working on our 'multi-org templating' feature from issue #58. We would have two types of organisation: an 'pre-founding unincorporated association' and the normal 'unincorporated association'. They'd share the core features, but behave differently (e.g. the pre-founding org doesn't need voting for changes to the membership and constitution) and appearance (e.g. the pre-founding org has additional copy explaining the setup process). And the moment of founding gives us a chance to code the process for moving an organisation from one type of organisation to another.

**Comment by dekstop** [comment]
The UX review session notes are hosted as a Google Groups page:
http://groups.google.com/group/oneclickorgs-devspace/web/notes-from-oco-usability-meeting-with-leisa-reichelt-2010-03-17

(Note that Google is deprecating the Files&Pages features of Google Groups soon. For now we can leave the document there, but at some point we'll have to move it somewhere else.)

**Comment by chrismear** [comment]
This ticket now at:

https://github.com/oneclickorgs/one-click-orgs/issues/118
