### ISSUE TITLE
proposals need index page

### ISSUE THREAD

**Issue by jberkel** [emmapersky/one-click-orgs#13]
/proposals => 404 at the moment

**Comment by dekstop** [comment]
I think I'm done with this, someone should sanity-check my changeset. http://github.com/dks/one-click-orgs/commit/80e34e0490ce1deedbe574fa3bdd47581f0e7179

I removed the Proposal#completed and Proposal#for class attributes, and replaced them with a Proposal#vote_by(member) method. Then updated the control centre controller+view to reflect that, and added a /proposals view

**Comment by jberkel** [comment]
missing template error on /proposals

**Comment by dekstop** [comment]
argh there you go http://github.com/dks/one-click-orgs/commit/5bb2eb1275ac693707adcdbfff60afb271500a7a

**Comment by jberkel** [comment]
added spec for proposals index page. closed by 366d7249e4df848822f1a973d3737533cac60ff1
