### ISSUE TITLE
Proposals should have comments

### ISSUE THREAD

**Issue by chrismear** [emmapersky/one-click-orgs#19]

**Comment by colintate** [comment]
Maybe not.  The ideal path would be for comments to be seen as separate from the voting, but if the conversation redefines/clarifies the proposal and the users don't then repropose/amend the proposal - then people could vote on the proposal under the assumption that they are voting for the clarification - which seeing as its not injected into the proposal could have consequences later.  This requires some thought.

**Comment by chrismear** [comment]
Agree that that's something that needs to be thought about carefully when we design this screen.

For instance, suppose we had the proposal text in a prominent box at the top of the screen, and the voting buttons were clearly visually attached to that box (perhaps even with very explicit button text, e.g. "Vote for this proposal" / "Vote against this proposal"). And then suppose the comments were visually demarcated (e.g. below the proposal, with a dividing line, in a 'secondary' colour/font style, etc.). Would that be enough?

**Comment by chrismear** [comment]
Sounds good.

**Comment by chrismear** [comment]
This ticket now at:

https://github.com/oneclickorgs/one-click-orgs/issues/19
