### ISSUE TITLE
Validations for data entered during induction process

### ISSUE THREAD

**Issue by chrismear** [emmapersky/one-click-orgs#30]

**Comment by dekstop** [comment]
Or to be more specific: the form handler throws an exception if not all members' "founding vote" checkboxes are checked during induction.

**Comment by chrismear** [comment]
Add some rudimentary validation to the induction process. Closed by 4a932f46e308b494974af02fb58edfb351cf2bea.

**Comment by chrismear** [comment]
This should have fixed the founding vote checkboxes problem too:

http://github.com/emmapersky/one-click-orgs/commit/4a932f46e308b494974af02fb58edfb351cf2bea#L0R206
