### ISSUE TITLE
induction: founder should be default member 1

### ISSUE THREAD

**Issue by dekstop** [emmapersky/one-click-orgs#43]
i.e., the founder's name and email should get inserted into the "Induction Members" form.

**Comment by dekstop** [comment]
(It happened twice now that I created two 'members' for the same person, because I re-entered the founder's name as an induction member.)

**Comment by chrismear** [comment]
Display the founding member above the members form during induction, to discourage the founder from entering their details again. Closed by 647ebea66c694aedf0f986c0602638e01e58331a.
