### ISSUE TITLE
Multiple classes of user

### ISSUE THREAD

**Issue by chrismear** [emmapersky/one-click-orgs#62]
E.g. for company limited by guarantee, may need 'directors' and 'members'.

**Comment by dekstop** [comment]
Here's my current understanding of the requirements for this feature:
- the system allows a developer or admin to define classes of users, and determine their level of access:
  - actions they may take (we'll need to enumerate these), e.g.: "may create proposal to change the constitution"
  - data sources they may "read" from (same)
- when people join the group they get assigned a user class. which one is dependent on how they joined:
  - most likely they join as a result of a specific proposal, e.g.: "proposal to appoint Chris Mear as director"
  - they might be part of the founding group (in which case it may make sense to amend the induction process with user class assignments)
  - other, e.g. London Hackspace members join by donating into a bank account (which means an automated process will create users and assign classes)
- a user may change their class, most likely via a proposal
- there is a "default" class for users who are not logged in

**Comment by dekstop** [comment]
Additionally:
- the user class system is described by a matrix of user classes x permissions
- this matrix is part of the constitution: it gets displayed as part of the constitution, and users can propose changes to it (to change permissions for an existing user class, maybe even to change which user classes are available)

**Comment by dekstop** [comment]
Examples for permissions:
- view the constitution
- create proposal
  - membership/user status (add user, change a user's class, eject user -- which may also just be a change in user class)
  - constitutional change
  - other (freeform text proposal)
- cast a vote (broken down by type of proposal)
- view proposal timeline, read proposals (may differentiate between proposals, decisions, failed proposals)
- view list of members, read other member's profiles/voting history (may differentiate between classes of users)

**Comment by dekstop** [comment]
The presence/absence of a permission affects:
- whether a form/piece of information gets displayed in a template (in some cases we may want to display a substitute text instead, in others we just leave it blank)
- whether a user can call a specific action on a specific controller class

And nothing else.

**Comment by dekstop** [comment]
Reflecting this matrix in our current data model will not be quite straightforward; Clauses, which model the storage layer, are just key/value pairs, whereas we will need to model a two-dimensional matrix. 

We can work around that as follows:
- permission clauses are boolean flags
- a permission clause encodes both the user class and permission in its "name" column (so a clause could be called "userclass_a_permission_to_eject_member", where "userclass" is a common prefix, "permission_to_eject_member" is the ID for a specific permission, and "a" refers to a named user class.)
- an absence of a clause (the default/initial state) implies an absence of that permission; this also ensures that we can add more permissions later without having to explicitly add Clauses for each user class

So to model permissions we need:
- a constitution-level Proposal class that allows to make changes to a user class' permissions (it's based on ChangeBooleanProposal, but takes care of encodes user class and permission name in the "clauses.name" column)
- a UserClass (MemberClass?) model that can load all permissions for a named user class, and that the Member class can join against

**Comment by dekstop** [comment]
Changing one permission of an existing user class is a simple constitutional change. Changing multiple permissions of an existing user class in one go would require us to introduce the notion of batched constitutional changes; we can probably leave that for a future version.

Less straightforward is the addition and removal of user classes:
- a proposal to remove a user class will need to include the name of a class that users will get migrated to instead
- a proposal to add a new user class will need to include a full set of permissions for this class (as before, we can probably leave that for a later version; in its absence this new user class will be powerless on inception, and permissions can be added one at a time via proposals. Tedious, but not a major problem for an early version)

**Comment by dekstop** [comment]
Let's do it as a proper relational model.
- Add a table "member_classes"
  - name
  - comment
- Add a foreign key to the clauses table

Note: the name of the clause still has to be unique to a membership class, since we rely on common names to record the history of a clause. I.e., clause names still are a concatenation of membership class name and permission name.

**Comment by dekstop** [comment]
Note that this will affect the voting system:
- we should not send out notification emails for proposals that a member cannot vote on
- the decision mechanism should only take into account members that can actually vote on a proposal (e.g. when determining majority)

**Comment by dekstop** [comment]
A good place to monitor development progress is the documentation, I'll keep updating it as I implement this:
http://github.com/dekstop/one-click-orgs/blob/master/doc/permissions.txt

**Comment by dekstop** [comment]
Merged the current state of the implementation into "trunk". 
- implements membership classes
- sets up a default organisation where all members are equal
- missing: proposal to create new membership class, proposal to modify existing membership class, proposal to delete existing membership class
- future dev work: more fine-grained voting permissions (e.g. split into vote on constitutional amendment, membership vote, etc.)

**Comment by chrismear** [comment]
This ticket now at:

https://github.com/oneclickorgs/one-click-orgs/issues/62
