### ISSUE TITLE
database.yml should be gitignored

### ISSUE THREAD

**Issue by chrismear** [emmapersky/one-click-orgs#70]
And a sample file added to the repo instead. Allows for easier per-server settings.

**Comment by dekstop** [comment]
done http://github.com/emmapersky/one-click-orgs/issues#issue/70

**Comment by dekstop** [comment]
Ah no, here: http://github.com/dekstop/one-click-orgs/commit/e0019867bace7a8c27e6458f9a901245afafd34a

**Comment by dekstop** [comment]
This has been committed and can be closed.
