### ISSUE TITLE
Cancel page has only OCO link?

### ISSUE THREAD

**Issue by colintate** [emmapersky/one-click-orgs#84]
When a person refuses the formation, they get to a page which says they can accept whenever they want, and can look at the oco website (wrong link).  

Shouldn't they get a link to their own website as well?  (if available?).  Are we capturing their domain?

**Comment by chrismear** [comment]
We're not capturing their web site details yet, no.

**Comment by chrismear** [comment]
This ticket now at:

https://github.com/oneclickorgs/one-click-orgs/issues/84
