### ISSUE TITLE
Refusing to join/joining later / Founding meetings

### ISSUE THREAD

**Issue by colintate** [emmapersky/one-click-orgs#85]
If the founding meeting allows for people to join at their leisure/refuse to join - they can join a year from now (as example).  Is this something that should be allowed?  Should the invite be rescindable by the inviter?  Downgraded?  Can the invited permanently rescind? 

Because we have a founding meeting (timed point of founding which is distinct from the timing of a person joining via OCO website), does this disparity cause issue?

**Comment by chrismear** [comment]
This ticket now at:

https://github.com/oneclickorgs/one-click-orgs/issues/85
