### ISSUE TITLE
modifying constitution - unnecessary proposals (rails3 only?)

### ISSUE THREAD

**Issue by colintate** [emmapersky/one-click-orgs#91]
If I modify the constitution and select the current voting option as my proposal, it sends out a proposal email - making it a valid proposal.

**Comment by chrismear** [comment]
Bug exists in Merb branch as well.

**Comment by chrismear** [comment]
I'm working on this.

**Comment by chrismear** [comment]
Don't create ChangeTextProposals if the text hasn't actually been changed. Closed by 994df4b42cffcf8f5179f7bd899c49c49b4c554c.
