### ISSUE TITLE
proposal case consistency

### ISSUE THREAD

**Issue by colintate** [emmapersky/one-click-orgs#92]
Proposals to change are not case consistent - and why are we publically showing an underline for organisation name?

Elucidian Angles    rejected

Change organisation_name to 'OCO on de Rails'   rejected

Change organisation_name to 'OCO on de Rails - III'     Vote in Progress

Change objectives to 'Taking OCO down the line to the shop, and then back again for tea.'   Vote in Progress

Change the constitution to prohibit holding, transferral or disposal of material assets and intangible assets   Vote in Progress

Change voting period to 24 hours    Vote in Progress

change general voting system to Supporting votes from more than half the members    Vote in Progress

change constitution voting system to Supporting votes from more than half the members   Vote in Progress

change membership voting system to Supporting votes from more than two thirds of the members    Vote in Progress

**Comment by chrismear** [comment]
'organisation_name' is related to a method name change: 2b7f3ec84ca44eca278bbe6a966b33ae00899873

**Comment by chrismear** [comment]
Have split the 'organisation_name' part of this ticket into #111. This ticket is now for case consistency only.

**Comment by chrismear** [comment]
This ticket now at:

https://github.com/oneclickorgs/one-click-orgs/issues/92
