### ISSUE TITLE
Majority voting systems should close proposals early if the proposal is guaranteed not to pass

### ISSUE THREAD

**Issue by chrismear** [emmapersky/one-click-orgs#98]
For example, if there are two members, and both have voted against the proposal, the proposals should close. At the moment, it just checks whether the number of 'for' votes is greater than (member_count \* fraction_needed) -- i.e. it will close early if the proposal has passed, but won't close early if the proposal is guaranteed to fail.

**Comment by dekstop** [comment]
Implemented in http://github.com/dekstop/one-click-orgs/commit/983b8b7f39e0fc95788c519432fadd5599e9a13d

**Comment by chrismear** [comment]
I tweaked this a little to keep Proposal#voting_system as an instance method instead of a class method: e0c874a5f59c1b4d8963858d6176be43fb640b7b
